CREATE DATABASE shop;
CREATE ROLE shop LOGIN;
GRANT ALL ON DATABASE shop TO shop;
CREATE ROLE viewer LOGIN;
GRANT CONNECT ON DATABASE shop TO viewer;
GRANT USAGE ON SCHEMA public TO viewer;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO viewer;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO viewer;
CREATE TABLE category (ID SERIAL, name CHAR(50) NOT NULL, PRIMARY KEY(ID));
INSERT INTO category (name) VALUES ('Sport'), ('Food'), ('Money'), ('Car'), ('Life');
CREATE TABLE items (ID SERIAL, name CHAR(50) NOT NULL, category CHAR(50) NOT NULL, price real, PRIMARY KEY(ID));
INSERT INTO items (name, category, price) VALUES ('BMW', 'Car', 1.00), ('Melkus', 'Car', 1.00), ('Lotec', 'Car', 1), ('Brennabor', 'Car', 1), ('Maybach', 'Car', 1.00), ('Audi', 'Car', 1.00), ('Mercedes-Benz', 'Car', 1.00), ('Porsche', 'Car', 1.00), ('VW', 'Car', 1.00);
UPDATE items SET price = 3.50 where ID IN (SELECT ID FROM items ORDER BY ID ASC LIMIT 1);
UPDATE items SET price = price * 1.1;
DELETE FROM items WHERE ID IN (SELECT ID FROM items ORDER BY ID ASC LIMIT 1 OFFSET 1);
SELECT * FROM items ORDER BY name;
SELECT * FROM items ORDER BY price DESC;
SELECT * FROM items ORDER BY price DESC LIMIT 3;
SELECT * FROM items ORDER BY price ASC LIMIT 3;
SELECT * FROM items ORDER BY price DESC LIMIT 3 OFFSET 3;
SELECT name FROM items ORDER BY price DESC LIMIT 1;
SELECT name FROM items ORDER BY price ASC LIMIT 1;
SELECT Count(*) FROM items;
SELECT AVG(price) AS PriceAverage FROM items;
CREATE VIEW view_items AS SELECT * FROM items ORDER BY price DESC LIMIT 3;
